#!/bin/bash

# Function to check if a string exists in a file
check_string_in_file() {
    local file=$1
    local string=$2
    grep -qF "$string" "$file"
}
function hide_output {
	OUTPUT=$(mktemp)
	set +e
	"$@" &> "$OUTPUT"
	E=$?
	set -e
	if [ $E != 0 ]; then
		# Something failed.
		echo
		echo "FAILED: $*"
		echo -----------------------------------------
		cat "$OUTPUT"
		echo -----------------------------------------
		exit $E
	fi
	rm -f "$OUTPUT"
}

function apt_get_quiet {
  DEBIAN_FRONTEND=noninteractive hide_output apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" "$@"
}

function apt_install {
	apt_get_quiet install "$@"
}
# Function to retrieve stored password
retrieve_password() {
    local filepath=$1
    if [ -f "$filepath" ]; then
        cat "$filepath"
    else
        echo "Error: Password file $filepath not found."
        exit 1
    fi
}
function restart_service {
	hide_output service "$1" restart
}
# Function to generate a random password with only letters and numbers
generate_password() {
    local length=$1
    local chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    local password=""
    for i in $(seq 1 $length); do
        password+=$(echo $chars | fold -w1 | shuf | head -n1)
    done
    echo $password
}



# Function to create or update the Postfix virtual alias file
update_postfix_virtual() {
    local domain=$1
    local username=$2

    if ! check_string_in_file "/etc/postfix/virtual" "$username@$domain"; then
        echo "$username@$domain $username" >> /etc/postfix/virtual
        postmap /etc/postfix/virtual
        echo "Updated /etc/postfix/virtual with $username@$domain."
    else
        echo "Entry for $username@$domain already exists in /etc/postfix/virtual."
    fi
}

# Function to update the Postfix main.cf configuration
update_postfix_maincf() {
    local domain=$1

    if ! check_string_in_file "/etc/postfix/main.cf" "virtual_alias_domains"; then
        echo "virtual_alias_domains = $domain" >> /etc/postfix/main.cf 2>/dev/null
    else
        sed -i "/^virtual_alias_domains/c\virtual_alias_domains = $domain" /etc/postfix/main.cf 2>/dev/null
    fi

    if ! check_string_in_file "/etc/postfix/main.cf" "virtual_alias_maps"; then
        echo "virtual_alias_maps = hash:/etc/postfix/virtual" >> /etc/postfix/main.cf 2>/dev/null
    fi

    if ! check_string_in_file "/etc/postfix/main.cf" "mydomain"; then
        echo "mydomain = $domain" >> /etc/postfix/main.cf 2>/dev/null
    else
        sed -i "/^mydomain/c\mydomain = $domain" /etc/postfix/main.cf 2>/dev/null
    fi

    if ! check_string_in_file "/etc/postfix/main.cf" "myorigin"; then
        echo "myorigin = \$mydomain" >> /etc/postfix/main.cf 2>/dev/null
    else
        sed -i "/^myorigin/c\myorigin = \$mydomain" /etc/postfix/main.cf 2>/dev/null
    fi

    if ! check_string_in_file "/etc/postfix/main.cf" "mydestination"; then
        echo "mydestination = \$myhostname, localhost.\$mydomain, localhost, \$mydomain" >> /etc/postfix/main.cf 2>/dev/null
    else
        sed -i "/^mydestination/c\mydestination = \$myhostname, localhost.\$mydomain, localhost, \$mydomain" /etc/postfix/main.cf 2>/dev/null
    fi

    echo "Postfix main.cf configuration updated....[OK]"
}


# Function to update Postfix configuration files
update_postfix_config() {
    local domain=$1
    local hostname=$2

    echo "Postfix Backup original configuration files.....[OK]"

    # Backup original configuration files
    cp /etc/postfix/main.cf /etc/postfix/main.cf.bak
    cp /etc/postfix/master.cf /etc/postfix/master.cf.bak

    echo "Downloading customized Postfix configuration files.....[OK]"

    # Download customized Postfix configuration files
    wget -qO /etc/postfix/main.cf https://raw.githubusercontent.com/gtmylab/mailx/main/postfix_main.cf
    wget -qO /etc/postfix/master.cf https://raw.githubusercontent.com/gtmylab/mailx/main/postfix_master.cf
    
    echo "Replacing Postfix placeholders with actual values.....[OK]"

    # Replace placeholders with actual values in Postfix configuration files
    sed -i "s/{EMAIL_DOMAIN}/$domain/g" /etc/postfix/main.cf 2>/dev/null
    sed -i "s/{EMAIL_DOMAIN}/$domain/g" /etc/postfix/master.cf 2>/dev/null
    sed -i "s/{HOSTNAME}/$hostname/g" /etc/postfix/main.cf 2>/dev/null
    sed -i "s/{HOSTNAME}/$hostname/g" /etc/postfix/master.cf 2>/dev/null

    echo "Restart Postfix to apply changes.....[OK]"
    # Restart Postfix to apply changes
    restart_service postfix

    echo "Postfix configuration updated....[OK]"
}


# Function to install Roundcube
install_roundcube() {
    local EMAIL_DOMAIN=$1
    local HOSTNAME=$2
    local ADMIN_MAILX_EMAIL=$3    
    local MYSQL_ROOT_PASSWORD=$(retrieve_password /usr/local/mysql_root_pwd.txt)
    local ROUNDCUBE_DB_PASSWORD=$(retrieve_password /usr/local/roundcube_db_pwd.txt)
    local ROUNDCUBE_DB_USER="roundcube"
    local ROUNDCUBE_DB_NAME="roundcubemail"
    local ROUNDCUBE_ADMIN_EMAIL="admin@$EMAIL_DOMAIN"
    local ROUNDCUBE_ADMIN_PASS=$(openssl rand -base64 12)

    # Update hostname and hosts file
    echo "$HOSTNAME" > /etc/hostname
    sed -i "s/127.0.0.1.*/127.0.0.1 localhost $HOSTNAME/" /etc/hosts
    hostnamectl set-hostname $HOSTNAME

        # Ensure /etc/mailname exists and update it if hostname is a valid FQDN
    # Ensure /etc/mailname exists and update it if hostname is a valid FQDN
    if [[ "$HOSTNAME" =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
        echo "$HOSTNAME" |  tee /etc/mailname > /dev/null
    else
        echo "Warning: '$HOSTNAME' is not a fully qualified domain name. /etc/mailname not changed."
    fi
    clear
        # Update system and install necessary packages
        echo "Installing packages needed for setup..."
        apt-get -qq update > /dev/null && apt-get -qq upgrade -y > /dev/null
        echo "System updated and upgraded successfully....[OK]"
        echo "[OK]"
        echo "Installing Software Properties..."
        apt_install software-properties-common
        echo "[OK]"
        echo "Adding PHP PPA repository..."
        LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y > /dev/null 2>&1
        echo "[OK]"
        # Update package list again after adding new repository
        apt-get -qq update > /dev/null
    # Install MySQL without interactive prompts
    echo "Installing MySQL (Database server)....."
    # Install MySQL without interactive prompts
    export DEBIAN_FRONTEND=noninteractive
    debconf-set-selections <<< "mysql-server mysql-server/root_password password $MYSQL_ROOT_PASSWORD"
    debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $MYSQL_ROOT_PASSWORD"
    apt-get -qq install -y mysql-server > /dev/null 

    # Create Roundcube database and user
    echo "MySQL (Database server) warnings [OK]....."
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $ROUNDCUBE_DB_NAME;"
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE USER IF NOT EXISTS '$ROUNDCUBE_DB_USER'@'localhost' IDENTIFIED BY '$ROUNDCUBE_DB_PASSWORD';"
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "GRANT ALL PRIVILEGES ON $ROUNDCUBE_DB_NAME.* TO '$ROUNDCUBE_DB_USER'@'localhost';"
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES;"
    echo "[OK]"

    # Install required packages for Roundcube
    echo "Installing Postfix & Dovecot (Mail server)..."
    apt_install postfix mailutils dovecot-imapd
    echo "[OK]"
    echo "Installing Apache (web server)..."
    echo "[OK]"
    apt_install apache2 libapache2-mod-fcgid libapache2-mod-php8.1 libapache2-mod-fcgid

        # Backup original configuration files
cp /etc/apache2/ports.conf /etc/apache2/ports.conf.bak
wget -qO /etc/apache2/ports.conf https://raw.githubusercontent.com/gtmylab/mailx/main/apache2/ports.conf

# Install PHP 8.1 and PHP 5.6 with FPM and required extensions
echo "Installing PHP 8.1 and PHP 5.6..."
apt_install php8.1 php8.1-fpm php8.1-cli php8.1-common php8.1-curl php8.1-mysql php8.1-xml php8.1-mbstring php8.1-zip php8.1-intl php8.1-pspell
apt_install php5.6 php5.6-fpm php5.6-cli php5.6-common php5.6-curl php5.6-mysql php5.6-xml php5.6-mbstring php5.6-zip php5.6-intl php5.6-pspell

# Enable required Apache modules
a2enmod actions fcgid alias proxy_fcgi

# Check PHP-FPM service name for PHP 8.1
PHPFPM_SERVICE=$(systemctl list-units --full --all | grep php8.1-fpm | awk '{print $1}')
if [ -z "$PHPFPM_SERVICE" ]; then
    echo "PHP 8.1 FPM service not found. Please check your PHP installation."
    exit 1
fi

# Configure PHP-FPM for PHP 8.1
mkdir -p /etc/php/8.1/fpm/pool.d
mkdir -p /etc/php/5.6/fpm/pool.d
wget -qO /etc/php/8.1/fpm/pool.d/www.conf https://raw.githubusercontent.com/gtmylab/mailx/main/php8/www.conf
# Configure PHP-FPM for PHP 5.6
wget -qO /etc/php/5.6/fpm/pool.d/www.conf https://raw.githubusercontent.com/gtmylab/mailx/main/php5/www.conf


sudo systemctl restart php8.1-fpm 2>/dev/null
sudo systemctl restart php5.6-fpm 2>/dev/null


# Configure Apache Virtual Hosts
#wget -qO /etc/apache2/sites-available/roundcube.conf https://raw.githubusercontent.com/gtmylab/mailx/main/apache2/roundcube.conf
#sed -i "s/ServerName HOSTNAME/ServerName $HOSTNAME/" /etc/apache2/sites-available/roundcube.conf

#wget -qO /etc/apache2/sites-available/mailx.conf https://raw.githubusercontent.com/gtmylab/mailx/main/apache2/mailx.conf
#sed -i "s/ServerName MAILHOSTNAME/ServerName $EMAIL_DOMAIN/" /etc/apache2/sites-available/mailx.conf
    echo "Installing additional Mailing Support..."
# Download and install
    mkdir -p  /var/www/html/mailx
    wget -qO  /var/www/html/mailx/index.php https://raw.githubusercontent.com/gtmylab/mailx/main/mailer.php
    chown -R www-data:www-data /var/www/html/mailx
    echo "Installing additional Mailing Support...[COMPLETED]"

    # Configure Apache for Roundcube
    cat <<EOF > /etc/apache2/sites-available/roundcube.conf
    <VirtualHost *:8080>
        ServerName $HOSTNAME
        DocumentRoot /var/www/html/roundcube

        <Directory /var/www/html/roundcube/>
            Options +FollowSymlinks
            AllowOverride All
            <IfModule mod_dir.c>
                DirectoryIndex index.php
            </IfModule>
        </Directory>

        <FilesMatch \.php$>
            SetHandler "proxy:unix:/run/php/php8.1-fpm.sock|fcgi://localhost"
         </FilesMatch>

        ErrorLog \${APACHE_LOG_DIR}/roundcube_error.log
        CustomLog \${APACHE_LOG_DIR}/roundcube_access.log combined
    </VirtualHost>
EOF

    # Configure Apache for Mailx
    cat <<EOF > /etc/apache2/sites-available/mailx.conf
    <VirtualHost *:8081>
        ServerName $EMAIL_DOMAIN
        DocumentRoot /var/www/html/mailx

        <Directory /var/www/html/mailx/>
            Options +FollowSymlinks
            AllowOverride All
            <IfModule mod_dir.c>
                DirectoryIndex index.php
            </IfModule>
        </Directory>

        <FilesMatch \.php$>
            SetHandler "proxy:unix:/run/php/php5.6-fpm.sock|fcgi://localhost"
        </FilesMatch>

        ErrorLog \${APACHE_LOG_DIR}/mailx_error.log
        CustomLog \${APACHE_LOG_DIR}/mailx_access.log combined
    </VirtualHost>
EOF
    # Disable old PHP version and enable PHP 8.1
    a2enmod php8.1
    systemctl restart apache2
    
    echo "[OK]"
    echo "[OK]"
    # Enable the sites and restart Apache
    a2ensite roundcube.conf
    a2ensite mailx.conf
    systemctl restart apache2

    # Download and install Roundcube
    echo "Downloading and installing Roundcube..."
    cd /var/www/html
    wget -q https://github.com/roundcube/roundcubemail/releases/download/1.5.0/roundcubemail-1.5.0-complete.tar.gz
    tar -xzf roundcubemail-1.5.0-complete.tar.gz
    mv roundcubemail-1.5.0 roundcube
    chown -R www-data:www-data /var/www/html/roundcube
    cd roundcube
    cp config/config.inc.php.sample config/config.inc.php
    echo "[OK]"
    echo "Configuring Roundcube...[OK]"

    # Configure Roundcube
        # Check if mail_domain exists and add if not

    sed -i "s/\$config\['db_dsnw'\].*/\$config\['db_dsnw'\] = 'mysql:\/\/$ROUNDCUBE_DB_USER:$ROUNDCUBE_DB_PASSWORD@localhost\/$ROUNDCUBE_DB_NAME';/" config/config.inc.php
    sed -i "s/\$config\['default_host'\].*/\$config\['default_host'\] = 'localhost';/" config/config.inc.php
    sed -i "s/\$config\['smtp_server'\].*/\$config\['smtp_server'\] = 'localhost';/" config/config.inc.php
    sed -i "s/\$config\['support_url'\].*/\$config\['support_url'\] = 'mailto:$ROUNDCUBE_ADMIN_EMAIL';/" config/config.inc.php

    sed -i "s/\$config\['smtp_port'\].*/\$config\['smtp_port'\] = 25;/" config/config.inc.php
    sed -i "s/\$config\['smtp_user'\].*/\$config\['smtp_user'\] = '';/" config/config.inc.php
    sed -i "s/\$config\['smtp_pass'\].*/\$config\['smtp_pass'\] = '';/" config/config.inc.php

   # if ! check_string_in_file config/config.inc.php "\$config['mail_domain']"; then
        sed -i "/\$config\['smtp_server'\]/i \$config['mail_domain'] = '$EMAIL_DOMAIN';" config/config.inc.php
  #  else
   #     sed -i "s/\$config\['mail_domain'\].*/\$config\['mail_domain'\] = '$EMAIL_DOMAIN';/" config/config.inc.php
    #fi


    echo "Initialize Roundcube database schema...[OK]"

    # Initialize Roundcube database schema
    sudo -u www-data ./bin/initdb.sh --dir=./SQL --create

    echo "Roundcube installation completed...[OK]"

    # Update Postfix configurations
    update_postfix_config "$EMAIL_DOMAIN" "$HOSTNAME"
   # install_mailx "$EMAIL_DOMAIN"

    # Add First User
    add_roundcube_user "admin" "$ROUNDCUBE_ADMIN_PASS"

 # Send notification to admin email
    send_notification_email "$ADMIN_MAILX_EMAIL" "http://$HOSTNAME:8080" "roundcube" "$ROUNDCUBE_ADMIN_PASS" "http://$EMAIL_DOMAIN:8081"


    # Output Roundcube admin details
    echo "Roundcube admin email: $ROUNDCUBE_ADMIN_EMAIL"
    echo "Roundcube admin password: $ROUNDCUBE_ADMIN_PASS"
}

# Function to add a new Roundcube user
add_roundcube_user() {
    #local ROUNDCUBE_DB_PASSWORD=$1
    local ROUNDCUBE_DB_USER="roundcube"
    local ROUNDCUBE_DB_NAME="roundcubemail"

    local username=$1
    local domain=$(retrieve_password /usr/local/roundcube_mail_domain.txt)
    local password=$2

    # Combine username and domain to create full email address
    email="$username@$domain"

    # Generate encrypted password for Linux user
    encrypted_password=$(openssl passwd -1 "$password")

    # Check if user already exists
    if id "$username" >/dev/null 2>&1; then
        echo "User $username already exists. Aborting."
        exit 1
    fi

    # Create user account
    useradd -m -s /bin/bash -p "$encrypted_password" "$username"
    echo "User $username created successfully."

    # Create Maildir for user
    mkdir -p /home/$username/Maildir
    chown -R $username:$username /home/$username/Maildir
    echo "Mail directory created for $username."

    # Retrieve MySQL root and Roundcube DB passwords
    MYSQL_ROOT_PASSWORD=$(retrieve_password /usr/local/mysql_root_pwd.txt)
    ROUNDCUBE_DB_PASSWORD=$(retrieve_password /usr/local/roundcube_db_pwd.txt)

    # Update Roundcube database with new user
    mysql -u $ROUNDCUBE_DB_USER -p"$ROUNDCUBE_DB_PASSWORD" $ROUNDCUBE_DB_NAME -e "INSERT INTO users (username, mail_host, created, last_login, language) VALUES ('$username', '$domain', NOW(), NOW(), 'en_US.utf8');"


    # Update Postfix configurations
    update_postfix_virtual "$domain" "$username"
    update_postfix_maincf "$domain"

    # Restart Postfix to apply changes
    restart_service postfix

    # Notify user via email
    send_welcome_email "$email" "$username"

    # Inform user creation details
    echo "==============================================="
    echo "New Roundcube User Details:"
    echo "Email: $email"
    echo "Username: $username"
    echo "Password: $password"
    echo "==============================================="
}

# Function to uninstall Roundcube, including database and user
uninstall_roundcube() {
    local MYSQL_ROOT_PASSWORD
    MYSQL_ROOT_PASSWORD=$(retrieve_password /usr/local/mysql_root_pwd.txt)

    # Drop Roundcube database and user
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "DROP DATABASE IF EXISTS roundcubemail;"
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "DROP USER 'roundcube'@'localhost';"

    # Remove Roundcube directory
    rm -rf /var/www/html/roundcube

    echo "Roundcube uninstallation completed."
}

# Function to uninstall Postfix, MySQL, and Roundcube
uninstall_all() {

    echo "Uninstalling Postfix, MySQL, and Roundcube..."
    # Call function to uninstall Roundcube database and user
    uninstall_roundcube

    # Stop services
    systemctl stop postfix
    systemctl stop apache2
    systemctl stop mysql

    # Remove packages
    sudo apt-get -y remove --purge postfix apache2 php* roundcube mysql-server mysql-client mysql-common mysql-server-core-* mysql-client-core-* > /dev/null
    sudo apt-get -y remove --purge mysql-server mysql-client mysql-common > /dev/null

    # Remove configuration files
    sudo rm -rf /var/lib/mysql
    sudo rm -rf /etc/mysql /var/lib/mysql /var/log/mysql*
    rm -rf /etc/postfix
    rm -rf /etc/mysql
    rm -rf /etc/apache2
    rm -rf /etc/roundcube
    rm -rf /var/www/html/roundcube
    sudo deluser mysql
    sudo delgroup mysql
    echo '[OK]'
    echo "Cleaning up system MailX System files..."
    sudo apt-get -y clean > /dev/null
    sudo apt-get -y autoremove > /dev/null
    sudo apt-get -y autoclean > /dev/null

    echo '[OK]'

    echo "Uninstallation completed."
}

# Function to send email notification
send_notification_email() {
    local recipient_email=$1
    local roundcube_url=$2
    local roundcube_db_user=$3
    local roundcube_db_password=$4
    local mailx_url=$5

    local subject="Roundcube Installation Successful"
    local body="Dear User,

The Roundcube installation was successful. Here are the details:

Roundcube Database Username: $roundcube_db_user
Roundcube Database Password: $roundcube_db_password

Please keep these details secure.

You can now access:
Webmail URL via: $roundcube_url
Mailx URL via: $mailx_url 

Best regards,
Your Server Team"

    echo "$body" | mail -s "$subject" "$recipient_email"
}

# Function to send welcome email to user
send_welcome_email() {

    local recipient_email=$1
    local roundcube_user=$2

    local subject="Welcome to Roundcube Webmail, $roundcube_user"
    local body="Dear User,\n\nCongratulations! 
    Your Roundcube email has been successfully set up.
    \n\nHere are your login details:\n\n
    Email Address: $recipient_email\n
    Username: $roundcube_user\n
    You can access your Roundcube webmail interface anytime\n\n
    Thank you,\nAdmin Team"

    echo -e "$body" | mail -s "$subject" "$recipient_email"
}


# Function to send welcome email to user
send_test_message() {

    # Install mailutils if not already installed
if ! dpkg -l | grep -q mailutils; then
    apt-get update
    apt-get install -y mailutils
fi

    local email_to=$1
    local email_subject=$2
    local email_body=$3
    local email_domain=$(retrieve_password /usr/local/roundcube_mail_domain.txt)

    echo -e "$email_body" | mail -s "$email_subject" -a "From: admin@$email_domain" "$email_to"
echo "Test mail sent to $email_to"

}

clear
# Main script starts here
echo "=== Roundcube and Postfix Installation ==="

# Check if script is run with root privileges
if [ "$(id -u)" != "0" ]; then
    echo "Error: This script must be run as root."
    exit 1
fi


# Select an option
echo "Select an option:"
echo "1. Install MailX"
echo "2. Add MailX User"
echo "3. Send a test mail"
echo "4. Uninstall Roundcube"
echo "5. Uninstall MailX"

read -p "Enter your choice (1, 2, 3, 4 or 5): " choice


case $choice in
    1)
    clear
# Welcome message
echo "Welcome to the MailX Server  Installation Script!"
echo
echo
# Loop until all required fields are entered correctly
while true; do
    # Ask for user input
    read -p "Please enter the email domain (e.g., example.com): " EMAIL_DOMAIN
    read -p "Please enter the hostname (e.g., mail.example.com): " HOSTNAME
    read -p "Please enter the admin email address: " ADMIN_MAILX_EMAIL

    echo

    # Validate inputs
    if [[ -z "$EMAIL_DOMAIN" || -z "$HOSTNAME" || -z "$ADMIN_MAILX_EMAIL" ]]; then
        echo "Error: All fields (Email Domain, Hostname, Admin Email) are mandatory. Please provide values for all."
        continue
    fi

    # Validate hostname
    if [[ ! "$HOSTNAME" =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
        echo "Error: '$HOSTNAME' is not a fully qualified domain name. Please enter a valid FQDN."
        continue
    fi

    # Display the entered information and ask for confirmation
    echo "You have entered the following information:"
    echo "Email Domain: $EMAIL_DOMAIN"
    echo "Hostname: $HOSTNAME"
    echo "Admin Email: $ADMIN_MAILX_EMAIL"
    echo
    read -p "Is this information correct? (y/n): " CONFIRM

    if [ "$CONFIRM" = "y" ]; then
        break
    else
        echo "Please re-enter the information."
    fi
done

# Generate MySQL root password and Roundcube DB password
MYSQL_ROOT_PASSWORD=$(generate_password 16)
ROUNDCUBE_DB_PASSWORD=$(generate_password 16)

# Store passwords and domain in files (example)
echo "$MYSQL_ROOT_PASSWORD" > /usr/local/mysql_root_pwd.txt
echo "$ROUNDCUBE_DB_PASSWORD" > /usr/local/roundcube_db_pwd.txt
echo "$EMAIL_DOMAIN" > /usr/local/roundcube_mail_domain.txt

# Install Roundcube with specified configurations
install_roundcube "$EMAIL_DOMAIN" "$HOSTNAME" "$ADMIN_MAILX_EMAIL"

  ;;
    2)
        read -p "Enter new username: " username
      #  read -p "Enter domain: " domain
        read -sp "Enter password for $username@$(retrieve_password /usr/local/roundcube_mail_domain.txt): " password
        echo

        # Call function to add Roundcube user
        add_roundcube_user "$username" "$password"

        ;;

    3)
        read -p "Email to: " email_to
        read -p "Subject: " email_subject
        read -p "Message Body: " email_body

      #  read -p "Enter domain: " domain
        echo

        # Call function to add Roundcube user
        send_test_message "$email_to" "$email_subject" "$email_body"

        ;;


    4)
    read -p "Are you sure you want to uninstall ? (yes or no): " RECONFIRM_UNINSTALL

    if [[ "$RECONFIRM_UNINSTALL" == "yes" ]]; then
        uninstall_roundcube
    else
        echo "Exiting."
    fi
    exit 1
    ;;

    5)
    read -p "Are you sure you want to uninstall Postfix, MySQL, and Roundcube ? (yes or no): " RECONFIRM_UNINSTALL

    if [[ "$RECONFIRM_UNINSTALL" == "yes" ]]; then
       # Call function to uninstall Postfix, MySQL, and Roundcube
        uninstall_all    
        else
        echo "Exiting."
    fi
    exit 1
    ;;

    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac
